# Generated by Django 6.0.4 on 2026-09-10 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NOTA', 'Nota'), ('INFORME', 'Informe'), ('ACTA', 'Acta de Entrega')], max_length=10, verbose_name='Tipo')),
                ('numero', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto')),
                ('remitente', models.CharField(max_length=150, verbose_name='Remitente')),
                ('destinatario', models.CharField(max_length=150, verbose_name='Destinatario')),
                ('cuerpo', models.TextField(verbose_name='Contenido')),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido')], default='BORRADOR', max_length=10, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('modificado_en', models.DateTimeField(auto_now=True, verbose_name='Modificado el')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemActa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='N° de Serie')),
                ('codigo_inventario', models.CharField(blank=True, max_length=100, verbose_name='Código Inventario')),
                ('condicion', models.CharField(choices=[('NUEVO', 'Nuevo'), ('USADO', 'Usado'), ('REPARADO', 'Reparado')], default='USADO', max_length=10, verbose_name='Condición')),
                ('observaciones', models.CharField(blank=True, max_length=255, verbose_name='Observaciones')),
                ('documento', models.ForeignKey(limit_choices_to={'tipo': 'ACTA'}, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documentos.documento')),
            ],
            options={
                'verbose_name': 'Ítem del Acta',
                'verbose_name_plural': 'Ítems del Acta',
            },
        ),
    ]
