# Generated by Django 6.0.4 on 2026-09-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='destinatario',
            field=models.TextField(blank=True, verbose_name='Destinatario'),
        ),
    ]
