# Generated by Django 6.0.4 on 2026-09-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documento_destinatario'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='receptor_dni',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='DNI de quien recibe'),
        ),
        migrations.AddField(
            model_name='documento',
            name='receptor_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre y Apellido de quien recibe'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('NOTA', 'Nota Técnica'), ('INFORME', 'Informe de Sistema'), ('ACTA', 'Acta de Entrega')], max_length=10, verbose_name='Tipo'),
        ),
    ]
