# Generated by Django 6.0.4 on 2026-09-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0003_documento_receptor_dni_documento_receptor_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cuerpo',
            field=models.TextField(blank=True, default='', verbose_name='Contenido'),
        ),
    ]
