# Generated by Django 6.0.4 on 2026-09-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_alter_documento_cuerpo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='adjuntos/%Y/%m/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(blank=True, max_length=255, verbose_name='Nombre Original')),
                ('tamano', models.PositiveIntegerField(default=0, verbose_name='Tamaño (bytes)')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Subido el')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='documentos.documento', verbose_name='Documento')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adjuntos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['creado_en'],
            },
        ),
    ]
