# Generated by Django 6.0.4 on 2026-09-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0005_adjunto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(choices=[('NOTA', 'Nota'), ('INFORME', 'Informe'), ('ACTA', 'Acta de Entrega')], max_length=10, verbose_name='Tipo'),
        ),
    ]
