# Generated by Django 6.0.4 on 2026-09-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0006_alter_documento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='destinatario_cargo',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Cargo del Destinatario'),
        ),
        migrations.AddField(
            model_name='documento',
            name='destinatario_nombre',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Nombre del Destinatario'),
        ),
    ]
