# Generated by Django 6.0.4 on 2026-09-23 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0007_documento_destinatario_cargo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaRecibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.CharField(blank=True, max_length=25, unique=True, verbose_name='N° Registro')),
                ('numero_origen', models.CharField(blank=True, max_length=100, verbose_name='N° Nota Externa / Ref.')),
                ('remitente_origen', models.CharField(max_length=255, verbose_name='Remitente / Procedencia')),
                ('fecha_recepcion', models.DateField(verbose_name='Fecha de Recepción')),
                ('hora_recepcion', models.TimeField(blank=True, null=True, verbose_name='Hora de Recepción')),
                ('asunto', models.CharField(max_length=255, verbose_name='Asunto / Motivo')),
                ('descripcion', models.TextField(blank=True, default='', verbose_name='Detalle o Contenido')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_TRAMITE', 'En Trámite'), ('RESPONDIDO', 'Respondida'), ('ARCHIVADO', 'Archivada')], default='PENDIENTE', max_length=15, verbose_name='Estado')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='notas_recibidas/%Y/', verbose_name='PDF Compilado')),
                ('observaciones', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('documento_respuesta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_que_responde', to='documentos.documento', verbose_name='Documento de Respuesta (Salida)')),
                ('recibido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas_recibidas', to=settings.AUTH_USER_MODEL, verbose_name='Recibido por')),
            ],
            options={
                'verbose_name': 'Nota Recibida',
                'verbose_name_plural': 'Notas Recibidas',
                'ordering': ['-fecha_recepcion', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PaginaNotaRecibida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pagina', models.PositiveIntegerField(default=1, verbose_name='Número de Página')),
                ('imagen', models.ImageField(upload_to='notas_recibidas/paginas/%Y/', verbose_name='Imagen / Escaneo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paginas', to='documentos.notarecibida', verbose_name='Nota')),
            ],
            options={
                'verbose_name': 'Página de Nota Recibida',
                'verbose_name_plural': 'Páginas de Nota Recibida',
                'ordering': ['numero_pagina', 'creado_en'],
            },
        ),
    ]
