# Generated by Django 6.0.4 on 2026-09-23 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0008_notarecibida_paginanotarecibida'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaginaNotaRecibida',
        ),
    ]
