# Generated by Django 6.0.4 on 2026-09-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0009_delete_paginanotarecibida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EMITIDO', 'Emitido'), ('ENTREGADO', 'Entregado')], default='BORRADOR', max_length=10, verbose_name='Estado'),
        ),
    ]
