# Generated by Django 6.0.4 on 2026-09-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0010_alter_documento_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='estado',
            field=models.CharField(choices=[('EMITIDO', 'Emitido'), ('ENTREGADO', 'Entregado')], default='EMITIDO', max_length=10, verbose_name='Estado'),
        ),
    ]
