# Generated by Django 6.0.4 on 2026-09-30 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0011_alter_documento_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='detalle_entrega',
            field=models.TextField(blank=True, default='', verbose_name='Detalle o Constancia de Entrega'),
        ),
    ]
