# Generated by Django 6.0.4 on 2026-10-01 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0012_documento_detalle_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='firma',
            field=models.CharField(choices=[('AMBOS', 'Darío y Alex (Ambas firmas)'), ('DARIO', 'Solo Darío'), ('ALEX', 'Solo Alex')], default='AMBOS', max_length=10, verbose_name='Firmas'),
        ),
    ]
